### PR TITLE
refactor(external_ref): Remove unnecessary UpdateExternalRefsJSONPayload type

### PR DESCRIPTION
**Pull request by deo002**
## Changes
- Remove unnecessary UpdateExternalRefsJSONPayload type

## Submitter Checklist

- [ ] Includes tests (if there is a feature changed/added)
- [ ] Includes docs ( if changes are user facing)
- [X] I have tested my changes locally.

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good. Needs test.

**Comment by GMishx** [comment]
I am unable to update the `external_ref` of a license, other fields can be updates. Please check the sample request bellow:

```shell
curl -X 'PATCH' \
  'http://localhost:8085/api/v1/licenses/MIT' \
  -H 'accept: application/json' \
  -H 'Authorization: mytoken' \
  -H 'Content-Type: application/json' \
  -d '{
  "external_ref": {
    "license_suffix": "GMishx"
  },
  "rf_risk": 4
}'
```

**Comment by deo002** [comment]
> I am unable to update the `external_ref` of a license, other fields can be updates. Please check the sample request bellow:
> 
> ```shell
> curl -X 'PATCH' \
>   'http://localhost:8085/api/v1/licenses/MIT' \
>   -H 'accept: application/json' \
>   -H 'Authorization: mytoken' \
>   -H 'Content-Type: application/json' \
>   -d '{
>   "external_ref": {
>     "license_suffix": "GMishx"
>   },
>   "rf_risk": 4
> }'
> ```
> 
> image

image

curl -X 'PATCH' \
  'http://localhost:5000/api/v1/licenses/MIT' \
  -H 'accept: application/json' \
  -H 'Authorization: token \
  -H 'Content-Type: application/json' \
  -d '{
  "rf_risk": 4,
  "external_ref": {
    "license_suffix": "GMishX"
  }
}'

Wierdly enough, its working for me. I'll look into it.

**Comment by GMishx** [comment]
The `external_ref` still cannot not updated during testing.

**Comment by GMishx** [comment]
From debugging, the default value for `external_ref` in my Database is `null`. This causes `gorm.Expr("jsonb_strip_nulls(external_ref || ?)", updates.ExternalRef)` to return `null` as `null || '{myjson}'::json` in PostgreSQL will return null.

I recommend to compare the `oldLicense.ExternalRef` and `updates.ExternalRef` in Go to create a final `ExternalRef` which can be passed to PostgreSQL without using the `||` operator. Doing so, we can be sure `null` on either side (existing or new value) should not make the entire JSON object as `null`.

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
