### PR TITLE
chore(reuse): set reuse lint in CI

### PR DESCRIPTION
**Pull request by GMishx**

### CODE REVIEW

**Comment by GMishx** [comment]
Any reason to close @k-avy ?

**Comment by avinal** [comment]
@GMishx I believe she did it my mistake.

**Comment by GMishx** [comment]
No worries for now but should not do it without a reason in future @k-avy

**Comment by k-avy** [comment]
Hii @GMishx, I did it out of confusion sorry for the trouble.  Sure, I will keep in mind for the next time. Thanks.

**Pull request closed without merging**
